openapi: 3.0.4
info:
  title: Weather Index API
  description: API to interact with the Weather Index platform
  version: 1.9.0

servers:
  - url: https://wi-backend.shuflduf.hackclub.app/api
    description: Production

components:
  schemas:
    Survivor:
      type: string
      enum:
        - "CommandoBody"
        - "HuntressBody"
        - "BanditBody"
        - "ToolbotBody"
        - "EngiBody"
        - "MageBody"
        - "MercBody"
        - "TreebotBody"
        - "LoaderBody"
        - "CrocoBody"
        - "CaptainBody"
        - "RailgunnerBody"
        - "VoidSurvivorBody"
        - "SeekerBody"
        - "FalseSonBody"
        - "ChefBody"
        - "DroneTechBody"
        - "DrifterBody"
    Difficulty:
      type: string
      enum:
        - "DIFFICULTY_EASY_NAME"
        - "DIFFICULTY_NORMAL_NAME"
        - "DIFFICULTY_HARD_NAME"
        - "ECLIPSE_1_NAME"
        - "ECLIPSE_2_NAME"
        - "ECLIPSE_3_NAME"
        - "ECLIPSE_4_NAME"
        - "ECLIPSE_5_NAME"
        - "ECLIPSE_6_NAME"
        - "ECLIPSE_7_NAME"
        - "ECLIPSE_8_NAME"
    Ending:
      type: string
      enum:
        - "StandardLoss"
        - "EscapeSequenceFailed"
        - "PrismaticTrialEnding"
        - "VoidEnding"
        - "DecompileEnding"
        - "RebirthEndingDef"
        - "ObliterationEnding"
        - "LimboEnding"
        - "MainEnding"

    RunReport:
      type: object
      properties:
        "id":
          type: integer
        "artifacts":
          type: array
          items:
            type: string
          example:
            - "Command"
        "bloodPurchases":
          type: integer
        "damageDealt":
          type: integer
        "damageTaken":
          type: integer
        "deaths":
          type: integer
        "difficulty":
          type: string
          $ref: "#/components/schemas/Difficulty"
        "distanceTraveled":
          type: integer
        "dronesPurchased":
          type: integer
        "eliteKills":
          type: integer
        "ending":
          type: string
          $ref: "#/components/schemas/Ending"
        "goldCollected":
          type: integer
        "goldPurchases":
          type: integer
        "healingRecieved":
          type: integer
        "highestDamageDealt":
          type: integer
        "highestLevel":
          type: integer
        "itemHistory":
          type: array
          items:
            type: object
            properties:
              "count":
                type: integer
              "id":
                type: integer
                description: Internal RoR2 item id
              "time":
                type: integer
                description: Time in seconds since the run started
        "items":
          type: object
          example:
            "52": 1
            "7": 2
            "96": 1
          description: Map of RoR2 item IDs to their count
        "itemsCollected":
          type: integer
        "kills":
          type: integer
        "lunarPurchases":
          type: integer
        "minionDamageDealt":
          type: integer
        "minionKills":
          type: integer
        "purchases":
          type: integer
        "score":
          type: integer
        "stageHistory":
          type: array
          items:
            type: string
          example:
            - "golemplains2"
            - "goolake"
        "stagesCompleted":
          type: integer
        "startTime":
          type: string
          format: date-time
          description: RFC 3339 style datetime with microsecond precision, e.g. 2026-07-28T10:05:23.155584
        "survivor":
          type: string
          $ref: "#/components/schemas/Survivor"
          example: "CommandoBody"
        "timeAliveSeconds":
          type: integer
        "turretsPurchased":
          type: integer
        "uploadTime":
          type: string
          format: date-time
          description: RFC 3339 style datetime with microsecond precision, e.g. 2026-07-28T10:05:23.155584
        "userId":
          type: string
          format: uuid
        "userImage":
          type: string
          format: uri
          nullable: true
          example: "https://example.com/image.png"
        "userUsername":
          type: string
        "userDisplayUsername":
          type: string
          nullable: true
    StatsRunReport:
      type: object
      properties:
        "timeAliveSeconds":
          type: integer
        "stagesCompleted":
          type: integer
        "score":
          type: integer
        "itemsCollected": 
          type: integer
        "dronesPurchased": 
          type: integer
        "turretsPurchased": 
          type: integer
        "kills": 
          type: integer
        "eliteKills": 
          type: integer
        "minionKills": 
          type: integer
        "deaths": 
          type: integer
        "damageDealt": 
          type: integer
        "minionDamageDealt": 
          type: integer
        "damageTaken": 
          type: integer
        "highestDamageDealt":
          type: integer
        "healingRecieved":
          type: integer
        "highestLevel":
          type: integer
        "goldCollected":
          type: integer
        "purchases": 
          type: integer
        "goldPurchases": 
          type: integer
        "bloodPurchases": 
          type: integer
        "lunarPurchases": 
          type: integer
        "distanceTraveled":
          type: integer

paths:
  /runs:
    get:
      summary: List of run reports
      responses:
        "200":
          description: JSON array of paginated runs
          content:
            application/json:
              schema:
                type: object
                properties:
                  "total":
                    type: integer
                  "runs":
                    type: array
                    items:
                      $ref: "#/components/schemas/RunReport"
      parameters:
        - name: by
          in: query
          schema:
            type: string
            default: "id"
          description: Which field to sort by.

        - name: sort
          in: query
          schema:
            type: string
            enum:
              - "ASC"
              - "DESC"
            default: "DESC"
          description: "Ascending or Descending sort"

        - name: fallback_sort
          in: query
          schema:
            type: string
            enum:
              - "ASC"
              - "DESC"
            default: "DESC"
          description: Fallback sort direction when multiple runs have the same values. Sorts by id

        - name: page
          in: query
          schema:
            type: integer
            default: 0

        - name: filters
          in: query
          schema:
            type: string
            default: "{}"
          description: >
            JSON object string.
            The keys are the property names and the values are arrays of string filters, depending on the field being filtered. <br>
            Ex. {"survivor": ["BanditBody","ToolbotBody"]} <br>
            Ex. {"score": ["<1000"]}

        - name: only
          in: query
          schema:
            type: array
            items:
              type: string
            default: "[]"
          description: >
            Which fields will be returned by the API. It's highly recommended to use this to avoid fetching unnecessary data. <br>
            Always returns player info (id, username, display name)

  /runs/{id}:
    get:
      summary: Run report by ID
      responses:
        "200":
          description: JSON object of a run report
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunReport"
        "404":
          description: Specified run does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Run 1 not found

      parameters:
        - name: id
          in: path
          description: Run ID
          required: true
          schema:
            type: integer

  /player/{username}:
    get:
      summary: Player info by username
      responses:
        "200":
          description: JSON object of user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  "id":
                    type: string
                    format: uuid
                  "image":
                    type: string
                    format: uri
                    nullable: true
                    example: "https://example.com/image.png"
                  "username":
                    type: string
                    example: "shuflduf"
                  "display_username":
                    type: string
                    nullable: true
                    example: "Shuflduf"
                  "about_me":
                    type: string
                    nullable: true
                    example: "how to close risky rain 2"
                  "region":
                    type: string
                    nullable: true
                    description: 2 letter country code
                    example: "CA"
                  "run_count":
                    type: integer
                  "win_count":
                    type: integer
                  "favourite_survivor":
                    type: string
                    $ref: "#/components/schemas/Survivor"
                  "favourite_difficulty":
                    type: string
                    $ref: "#/components/schemas/Difficulty"
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                
      parameters:
        - name: username
          in: path
          description: Player Username
          required: true
          schema:
            type: string

  /stats/overall:
    get:
      summary: Overall info about all runs played
      responses:
        "200":
          description: JSON object of various properties
          content:
            application/json:
              schema:
                type: object
                properties:
                  "runCount":
                    type: integer
                  "winCount":
                    type: integer
                  "playtimeSeconds":
                    type: integer
                  
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                 
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string
        

  /stats/sum:
    get:
      summary: Summed stats of all runs
      responses:
        "200":
          description: JSON object of certain summed stats
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatsRunReport"
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                  
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string

  /stats/avg:
    get:
      summary: Averaged stats of all runs
      responses:
        "200":
          description: JSON object of certain averaged stats
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatsRunReport"
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                  
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string

  /stats/survivors:
    get:
      summary: Survivors played for all runs
      responses:
        "200":
          description: JSON object of survivors and their run counts
          content:
            application/json:
              schema:
                type: object
                example:
                  "CaptainBody": 3
                  "CommandoBody": 1
                  "RailgunnerBody": 2
                  "SeekerBody": 1
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                 
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string

  /stats/stages:
    get:
      summary: Stages played for all runs
      description: More accurately described as "what stage did each run end on"
      responses:
        "200":
          description: JSON object of stage number and how many runs ended there
          content:
            application/json:
              schema:
                type: object
                example:
                  "1": 5
                  "2": 13
                  "3": 1
                  "4": 2
                  "5": 51
                  "6": 8
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                 
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string

  /stats/artifacts:
    get:
      summary: Artifacts used for all runs
      responses:
        "200":
          description: JSON object of artifact names and their usage counts
          content:
            application/json:
              schema:
                type: object
                example:
                  "Bomb": 2
                  "Command": 545930459830945
                  "EliteOnly": 1
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                 
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string

  /stats/difficulties:
    get:
      summary: Difficulties played for all runs
      responses:
        "200":
          description: JSON object of difficulties' names and how many times they were played
          content:
            application/json:
              schema:
                type: object
                example:
                  "DIFFICULTY_EASY_NAME": 9
                  "DIFFICULTY_HARD_NAME": 12
                  "DIFFICULTY_NORMAL_NAME": 16
                  "ECLIPSE_1_NAME": 5
                  "ECLIPSE_2_NAME": 7
                  "ECLIPSE_3_NAME": 6
                  "ECLIPSE_4_NAME": 6
                  "ECLIPSE_5_NAME": 4
                  "ECLIPSE_6_NAME": 2
                  "ECLIPSE_7_NAME": 3
                  "ECLIPSE_8_NAME": 5
        "404":
          description: Specified player does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  "error":
                    type: string
                    example: Player `username` not found
                 
      parameters:
        - name: username
          in: query
          description: Player Username
          required: false
          schema:
            type: string


